<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <AssemblyName>MongoFramework.AspNetCore.Identity</AssemblyName>
    <Title>MongoFramework.AspNetCore.Identity</Title>
    <Description>.Net Core Identity providers for MongoFramework</Description>
    <PackageTags>$(PackageBaseTags)</PackageTags>
    <Authors>John Campion Jr</Authors>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="9.0.9" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="9.0.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>

</Project>