<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>MongoFramework.AspNetCore.Identity</AssemblyName>
    <Title>jcamp.MongoFramework.AspNetCore.Identity</Title>
    <PackageId>jcamp.MongoFramework.AspNetCore.Identity</PackageId>
    <Description>.Net Core Identity providers for MongoFramework</Description>
    <PackageTags>$(PackageBaseTags)</PackageTags>
    <Authors>John Campion Jr</Authors>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="jcamp.MongoFramework" Version="3.0.0" />
  </ItemGroup>

</Project>
